development:
  adapter: sqlite3
  database: db/ruby-getting-started_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/ruby-getting-started_development.sqlite3
  pool: 5
  timeout: 5000